### ISSUE TITLE
PostCSS loops

### ISSUE THREAD

**Issue by joscha** [joscha/node-detective-postcss#8]
Such as:

```css
@for $i from 0 to 165 by 15 {
    .x-$i {
        background: url('./bg-$(i).png');
    }
}
```
