### ISSUE TITLE
-webkit-image-set

### ISSUE THREAD

**Issue by joscha** [joscha/node-detective-postcss#9]
```css
.x {
  cursor: -webkit-image-set(url('./png/a.png') 1x, url('./png/a@2x.png') 2x) 12 12, auto;
}
```
